spring:
  profiles:
    active: dev
  application:
    name: chat-server
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      file-size-threshold: 2KB
      max-request-size: 215MB

server:
  port: 8088

application:
  db:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    urlDB: "jdbc:mysql://${urldb:lmc8ixkebgaq22lo.chr7pe7iynqr.eu-west-1.rds.amazonaws.com}:3306/${dbName:qbl8g0n8bxn10ck8}?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    userName: ${username:v6bxrdk9dzmuy7gc}
    password: ${password:fppulvxi0obkyq3z}